sections = ["intro|methods", "materials",
			"materials-methods", "materials|methods", "method", "methods", "Method",
			"methods|conclusions", "methods|results", "methods|subjects",
			"subjects", "subjects|methods", "Animal Studies", "Animal experiments", "Animal model", "Animal models",
			"Animal studies", "Animals", "Animals and diets", "Animals and experimental design", "Animals and housing",
			"Animals.", "Characteristics of the patients", "Characteristics of the study population",
			"Demographic characteristics", "Demographic data", "Demographics", "Demography", "Design",
			"Design and Methods", "Design and methods", "Design and setting", "Design:", "Drug administration",
			"Drug preparation and administration", "Drug preparation", "Eligibility", "Case","Case presentation", "Glycaemic Control",
			"Eligibility criteria", "Experiment Setup", "Experimental", "Experimental Design", "Experimental Methods",
			"Experimental Protocol", "Experimental Section", "Experimental Set Up", "Experimental Set-Up",
			"Experimental Setup", "Experimental animals", "Experimental design", "Experimental groups",
			"Experimental procedure", "Experimental procedures", "Experimental protocol", "Experimental protocols",
			"Experimental setup", "Experiments", "Experiments and Discussion", "Experiments and Results", "Human samples",
			"Human subjects", "Inclusion and exclusion criteria", "Inclusion criteria", "Inclusion/exclusion criteria",
			"Laboratory measurements", "Laboratory methods", "Laboratory tests", "METHOD:", "METHODS", "METHODS:",
			"Material", "Material&Methods", "Material and Methods", "Material and Methods:", "Material and methods", "Material/Methods",
			"Materials", "Materials and Methods", "Materials and method", "Materials and methods", "Method",
			"Methodological considerations", "Methodology", "Methodology and Findings", "Methodology and Principal Findings",
			"Methodology/Findings", "Methodology/Principal Finding", "Methodology/Principal Findings",
			"Methodology/Principal findings", "Methods", "Methods Findings", "Methods and Findings", "Methods and Results",
			"Methods and design", "Methods and materials", "Methods and results", "Methods", "Methods/Design",
			"Methods/Principal Findings", "Methods/Results", "Methods/design", "Methods:", "Mice", "Mice.",
			"Participant Characteristics", "Participant characteristics", "Participant recruitment", "Participants",
			"Participants and Methods", "Participants and Procedures", "Participants and recruitment", "Patient Population",
			"Patient Selection", "Patient and tumor characteristics", "Patient characteristics", "Patient cohort",
			"Patient demographics", "Patient eligibility", "Patient material", "Patient population", "Patient samples",
			"Patient selection", "Patients", "Patients and Methods", "Patients and controls", "Patients and methods",
			"Patients and samples", "Patients and specimens", "Patients and tissue samples", "Patients and tissue specimens",
			"Patients and treatment", "Patients and treatments", "Patients characteristics", "Patients' characteristics",
			"Procedures",
			"Studies", "Study Design", "Study Design.", "Study Participants", "Study Population", "Study Protocol",
			"Study characteristics", "Study cohort", "Study design", "Study design and participants",
			"Study design and patient selection", "Study design and patients", "Study design and population",
			"Study design and protocol", "Study design and sample", "Study design and setting", "Study design and subjects",
			"Study design and treatment", "Study group", "Study participants", "Study population", "SUBJECTS, MATERIALS AND METHODS",
			"Study population and data collection", "Study population and design", "Study populations", "Study protocol",
			"Study sample", "Study subjects", "Subject characteristics", "Subject demographics", "Subject recruitment",
			"Subjects", "Subjects and methods", "The Study", "The study", "Trial design", "Treatment, outcome and follow up"]

titles= ["Animal Studies", "Animal experiments", "Animal model", "Animal models",
        "Animal studies", "Animals", "Animals and diets", "Animals and experimental design",
        "Animals and housing", "Animals.", "Case presentation", "Case Report", "CASE REPORT", "Cohort characteristics", "Demographic characteristics",
        "Demographic data", "Demographics", "Demography", "Description", "Descriptive analysis", "Descriptive data",
        "Descriptive statistics", "Design", "Design and Methods", "Design and methods", "Design and setting",
        "Design:", "Drugs", "Drug treatment", "Eligibility", "Eligibility criteria", "Experimental Design", "Experimental Methods",
        "Experimental Protocol", "Experimental Section", "Experimental Set Up", "Experimental Set-Up",
        "Experimental Setup", "Experimental animals", "Experimental design", "Experimental groups",
        "Experimental protocol", "Experimental protocols", "Experimental setup", "Experiments", "Glycemic control",
        "Experiments and Discussion", "Experiments and Results", "Human subjects", "In vivo", "Interventions","Intervention",
        "METHOD:", "METHODS", "METHODS:","Method","Medications, doses and preparation",
        "Methods",
        "Material", "Material and Methods", "Material and Methods:", "Material and methods", "Material/Methods",
        "Materials", "Materials and Methods", "Materials and method", "Materials and methods", "Methodology", "Mice", "Mice.",
        "Participant Characteristics", "Participant characteristics", "Participant recruitment", "Participants", "Patient and observation",
        "Participants and Methods", "Participants and Procedures", "Participants and recruitment", "Patient Population",
        "Patient Selection", "Patient and tumor characteristics", "Patient characteristics", "Patient cohort",
        "Patient demographics", "Patient eligibility", "Patient material", "Patient population", "Patient samples",
        "Patient selection", "Patients", "Patients and Methods", "Patients and controls", "Patients and methods",
        "Patients and samples", "Patients and specimens", "Patients and tissue samples", "Patients and tissue specimens",
        "Patients and treatment", "Patients and treatments", "Patients characteristics", "Patients' characteristics", "Randomization",
        "Sample size", "Sample size and statistical analysis", "Sample size calculation and justification",
        "Selection of participants", "Sociodemographic characteristics", "Study Design", "Study Design.",
        "Study Participants", "Study Population", "Study Protocol", "Study characteristics", "Study cohort", "Study design",
        "Study design and participants", "Study design and patient selection", "Study design and patients",
        "Study design and population", "Study design and protocol", "Study design and sample", "Study design and setting" ,
        "Study design and subjects", "Study design and treatment", "Study group", "Study participants",
        "Study population", "Study population and data collection", "Study population and design", "Study populations",
        "Study procedures", "Study protocol", "Study subjects", "Study treatments", "Surgical procedure",
        "Treatment regimen", "db/db Mice", "Patient population and study design", "Treatments", "Study Treatments and Assessments"]
